In [1]:
import pdfplumber
import re
import pandas as pd

In [4]:
pdf = pdfplumber.open("bpfbouw.pdf")

In [9]:
tabs = []

for page in pdf.pages:
    text = page.extract_text()
    if text:
            pattern = re.compile(r'^(.+?)\s+([\d.]+,\d+)$', re.MULTILINE)
            matches = pattern.findall(text)
            tabs.append(matches)

tabs

[[('Afrika', '87.955,7'),
  ('Egypte', '487,6'),
  ('Commercial International Bank - Egypt (CIB)', '487,6'),
  ('Zuid-Afrika', '87.468,1'),
  ('Anglo American Platinum Ltd', '168,6'),
  ('Anglogold Ashanti Plc', '4.441,8'),
  ('Bid Corp Ltd', '624,4'),
  ('Capitec Bank Holdings Ltd', '4.625,4'),
  ('Clicks Group Ltd', '3.470,9'),
  ('Discovery Ltd', '592,6'),
  ('FirstRand Ltd', '11.586,9'),
  ('Foschini Group Ltd', '530,7'),
  ('Gold Fields Ltd', '10.231,2'),
  ('Growthpoint Properties Ltd', '158,4'),
  ('Hyprop Investments Ltd', '629,8'),
  ('Impala Platinum Holdings Ltd', '2.143,6'),
  ('Investec Ltd', '1.062,2'),
  ('JSE Ltd', '27,4'),
  ('Momentum Group Ltd', '677,4'),
  ('Mr Price Group Ltd', '1.431,3'),
  ('Naspers Ltd', '16.384,3'),
  ('Nedbank Group Ltd', '3.024,8'),
  ('NEPI Rockcastle NV', '1.174,8'),
  ('Netcare Ltd', '9,1'),
  ('Ninety One Ltd', '87,1'),
  ('Northam Platinum Holdings Ltd', '124,8'),
  ('Old Mutual Ltd', '1.245,0'),
  ('OUTsurance Group Ltd', '3.356,5'),
  ('Pepkor Holdings Ltd', '221,4'),
  ('Remgro Ltd', '354,9'),
  ('Resilient REIT Ltd', '49,6'),
  ('Reunert Ltd', '191,5'),
  ('Sanlam Ltd', '9.072,5'),
  ('Santam Ltd', '904,6'),
  ('Shoprite Holdings Ltd', '601,9'),
  ('Standard Bank Group Ltd', '4.534,9'),
  ('Vodacom Group Ltd', '3.425,3'),
  ('Woolworths Holdings Ltd/South Africa', '302,3'),
  ('Azië', '2.899.901,9'),
  ('China', '358.071,9'),
  ('AAC Technologies Holdings Inc', '1.264,0'),
  ('Agricultural Bank of China Ltd', '4.568,7'),
  ('Air China Ltd', '50,8'),
  ('Alibaba Group Holding Ltd', '16.047,7'),
  ('Alibaba Health Information Technology Ltd', '99,8'),
  ('Alibaba Pictures Group Ltd', '8,5')],
 [('Angelalign Technology Inc', '19,7'),
  ('ANTA Sports Products Ltd', '6.093,2'),
  ('Bank of China - Luxembourg Branch', '4.356,1'),
  ('Bank of Communications Co Ltd', '329,1'),
  ('Bank of Ningbo Co Ltd', '48,5'),
  ('Beijing Enterprises Holdings Ltd', '79,6'),
  ('Beijing Kingsoft Office Software Inc', '45,2'),
  ('Beijing New Building Materials PLC', '544,6'),
  ('Beijing Roborock Technology Co Ltd', '20,2'),
  ('Bilibili Inc', '187,4'),
  ('Blue Moon Group Holdings Ltd', '19,4'),
  ('BOC Aviation Ltd', '589,7'),
  ('BOC International China Co Ltd', '20,3'),
  ('Bosideng International Holdings Ltd', '3.336,8'),
  ('Centre Testing International Group Co Ltd', '595,0'),
  ('CGN Power Co Ltd', '42,2'),
  ('China CITIC Bank Corp Ltd', '1.482,5'),
  ('China Communications Services Corp Ltd', '2.634,4'),
  ('China Construction Bank Corp', '12.704,3'),
  ('China Education Group Holdings Ltd', '13,0'),
  ('China Galaxy Securities Co Ltd', '505,4'),
  ('China International Capital Corp Ltd', '99,7'),
  ('China Jushi Co Ltd', '15,0'),
  ('China Life Insurance Co Ltd', '1.583,0'),
  ('China Longyuan Power Group Corp Ltd', '128,0'),
  ('China Meidong Auto Holdings Ltd', '174,7'),
  ('China Mengniu Dairy Co Ltd', '268,2'),
  ('China Merchants Bank Co Ltd', '4.863,3'),
  ('China Merchants Port Holdings Co Ltd', '122,2'),
  ('China Merchants Securities Co Ltd', '132,8'),
  ('China Minsheng Banking Corp Ltd', '28,6'),
  ('China Overseas Land & Investment Ltd', '1.197,6'),
  ('China Pacific Insurance Group Co Ltd', '5.855,2'),
  ('China Resources Gas Group Ltd', '1.145,4'),
  ('China Resources Land Ltd', '3.843,4'),
  ('China Resources Microelectronics Ltd', '35,5'),
  ('China Resources Mixc Lifestyle Services Ltd', '452,4'),
  ('China State Construction International Holdings Ltd', '122,9'),
  ('China Taiping Insurance Holdings Co Ltd', '1.277,4'),
  ('China Tourism Group Duty Free Corp Ltd', '66,1'),
  ('China XD Electric Co Ltd', '44,2'),
  ('China Yangtze Power Co Ltd', '4.094,4'),
  ('China Zheshang Bank Co Ltd', '37,6'),
  ('Chinasoft International Ltd', '65,6'),
  ('Chow Tai Fook Jewellery Group Ltd', '93,0'),
  ('CITIC Ltd', '358,2')],
 [('CITIC Securities Co Ltd', '262,2'),
  ('Contemporary Amperex Technology Co Ltd', '14.727,3'),
  ('COSCO SHIPPING Ports Ltd', '40,6'),
  ('Country Garden Holdings Co Ltd', '16,7'),
  ('CSC Financial Co Ltd', '298,4'),
  ('Daqin Railway Co Ltd', '23,5'),
  ('Dongyue Group Ltd', '32,0'),
  ('East Buy Holding Ltd', '27,9'),
  ('East Money Information Co Ltd', '124,9'),
  ('ENN Energy Holdings Ltd', '4.116,8'),
  ('ENN Natural Gas Co Ltd', '36,1'),
  ('Eve Energy Co Ltd', '29,7'),
  ('FIH Mobile Ltd', '164,1'),
  ('Foshan Haitian Flavouring & Food Co Ltd', '137,0'),
  ('Founder Securities Co Ltd', '53,2'),
  ('Foxconn Industrial Internet Co Ltd', '91,5'),
  ('Full Truck Alliance Co Ltd', '1.939,8'),
  ('Fuyao Glass Industry Group Co Ltd', '781,1'),
  ('GalaxyCore Inc', '18,0'),
  ('Ganfeng Lithium Group Co Ltd', '168,7'),
  ('Geely Automobile Holdings Ltd', '2.792,0'),
  ('GF Securities Co Ltd', '125,3'),
  ('Gotion High-tech Co Ltd', '151,2'),
  ('Gree Electric Appliances Inc of Zhuhai', '2.284,7'),
  ('Greentown China Holdings Ltd', '44,7'),
  ('Guangdong Investment Ltd', '70,5'),
  ('Guangzhou Baiyunshan Pharmaceutical Holdings Co Ltd', '19,8'),
  ('Guolian Securities Co Ltd', '25,1'),
  ('Guosen Securities Co Ltd', '28,0'),
  ('Guoyuan Securities Co Ltd', '10,5'),
  ('H World Group Ltd', '1.194,6'),
  ('Haidilao International Holding Ltd', '616,5'),
  ('Haier Smart Home Co Ltd', '5.531,5'),
  ('Haitian International Holdings Ltd', '73,0'),
  ('Hangzhou First Applied Material Co Ltd', '13,4'),
  ('Hengan International Group Co Ltd', '104,5'),
  ('Huatai Securities Co Ltd', '1.239,6'),
  ('Hygeia Healthcare Holdings Co Ltd', '26,5'),
  ('Industrial Bank Co Ltd', '104,6'),
  ('Industrial Securities Co Ltd', '21,1'),
  ('Inner Mongolia Yili Industrial Group Co Ltd', '3.980,0'),
  ('JA Solar Technology Co Ltd', '8,6'),
  ('JCET Group Co Ltd', '14,0'),
  ('JD Health International Inc', '200,2'),
  ('JD Logistics Inc', '381,2')],
 [('JD.com Inc', '13.452,1'),
  ('Jiangsu Hengli Hydraulic Co Ltd', '32,8'),
  ('Jiangsu Zhongtian Technology Co Ltd', '167,8'),
  ('Jinxin Fertility Group Ltd', '28,1'),
  ('Juneyao Airlines Co Ltd', '28,0'),
  ('KE Holdings Inc', '3.599,8'),
  ('Kingdee International Software Group Co Ltd', '3.046,1'),
  ('Kingsoft Corp Ltd', '1.874,9'),
  ('Kuaishou Technology', '4.485,1'),
  ('Kunlun Energy Co Ltd', '1.769,9'),
  ('Kweichow Moutai Co Ltd', '1.702,9'),
  ('Lenovo Group Ltd', '2.879,2'),
  ('Li Auto Inc', '1.666,8'),
  ('Liaoning Port Co Ltd', '50,7'),
  ('Longfor Group Holdings Ltd', '88,9'),
  ('LONGi Green Energy Technology Co Ltd', '35,5'),
  ('Meituan', '26.307,9'),
  ('Midea Group Co Ltd', '6.513,0'),
  ('MINISO Group Holding Ltd', '123,2'),
  ('Minth Group Ltd', '602,5'),
  ('MMG Ltd', '959,1'),
  ('Montage Technology Co Ltd', '12,5'),
  ('NARI Technology Co Ltd', '4.891,5'),
  ('NetEase Inc', '10.007,9'),
  ('New China Life Insurance Co Ltd', '140,4'),
  ('New Oriental Education & Technology Group Inc', '2.305,2'),
  ('Nongfu Spring Co Ltd', '346,7'),
  ('Onewo Inc', '21,7'),
  ('Orient Securities Co Ltd/China', '643,6'),
  ('PDD Holdings Inc', '8.917,0'),
  ("People's Insurance Co Group of China Ltd/The", '262,5'),
  ('Pharmaron Beijing Co Ltd', '30,1'),
  ('PICC Property & Casualty Co Ltd', '10.483,1'),
  ('Ping An Bank Co Ltd', '44,3'),
  ('Ping An Healthcare and Technology Co Ltd', '0,0'),
  ('Ping An Insurance Group Co of China Ltd', '17.098,5'),
  ('Pop Mart International Group Ltd', '1.345,6'),
  ('Postal Savings Bank of China Co Ltd', '291,4'),
  ('Qifu Technology Inc', '2.469,0'),
  ('Sany Heavy Equipment International Holdings Co Ltd', '37,1'),
  ('Sany Heavy Industry Co Ltd', '2.899,0'),
  ('SG Micro Corp', '18,7'),
  ('Shandong Hi-speed Co Ltd', '1.409,7'),
  ('Shanghai Baosight Software Co Ltd', '562,1'),
  ('Shanghai Electric Group Co Ltd', '81,9'),
  ('Shanghai Fudan Microelectronics Group Co Ltd', '16,5')],
 [('Shanghai M&G Stationery Inc', '23,4'),
  ('Shanghai MicroPort MedBot Group Co Ltd', '200,3'),
  ('Shanghai Pharmaceuticals Holding Co Ltd', '73,9'),
  ('Shanghai Pudong Development Bank Co Ltd', '5.299,8'),
  ('Shenwan Hongyuan Group Co Ltd', '18,6'),
  ('Shenzhen Inovance Technology Co Ltd', '116,0'),
  ('Shenzhen Mindray Bio-Medical Electronics Co Ltd', '2.477,4'),
  ('Shenzhen New Industries Biomedical Engineering Co Ltd', '29,7'),
  ('Shenzhen YUTO Packaging Technology Co Ltd', '19,3'),
  ('Shenzhou International Group Holdings Ltd', '1.063,0'),
  ('Sinolink Securities Co Ltd', '21,3'),
  ('Sinoma International Engineering Co', '25,5'),
  ('Sinotruk Hong Kong Ltd', '76,2'),
  ('SooChow Securities Co Ltd', '19,6'),
  ('Sunac Services Holdings Ltd', '31,7'),
  ('Sungrow Power Supply Co Ltd', '2.215,6'),
  ('Sunny Optical Technology Group Co Ltd', '2.107,1'),
  ('Sunwoda Electronic Co Ltd', '197,4'),
  ('TAL Education Group', '246,1'),
  ('TCL Zhonghuan Renewable Energy Technology Co Ltd', '19,7'),
  ('Tencent Holdings Ltd', '36.817,4'),
  ('Tianqi Lithium Corp', '23,0'),
  ('Tongcheng Travel Holdings Ltd', '1.632,1'),
  ('TravelSky Technology Ltd', '47,2'),
  ('Trip.com Group Ltd', '11.792,9'),
  ('Tsingtao Brewery Co Ltd', '4.405,3'),
  ('Uni-President China Holdings Ltd', '56,8'),
  ('Universal Scientific Industrial Shanghai Co Ltd', '13,6'),
  ('Vipshop Holdings Ltd', '780,0'),
  ('Wanhua Chemical Group Co Ltd', '384,1'),
  ('Weichai Power Co Ltd', '2.043,6'),
  ('Wens Foodstuff Group Co Ltd', '47,2'),
  ('Will Semiconductor Co Ltd Shanghai', '1.203,6'),
  ('Wingtech Technology Co Ltd', '10,3'),
  ('WUS Printed Circuit Kunshan Co Ltd', '92,6'),
  ('WuXi AppTec Co Ltd', '134,5'),
  ('Xiaomi Corp', '8.664,8'),
  ('Xinyi Solar Holdings Ltd', '1.314,2'),
  ('XPeng Inc', '322,3'),
  ('Yifeng Pharmacy Chain Co Ltd', '1.047,3'),
  ('Yihai International Holding Ltd', '23,4'),
  ('Yonyou Network Technology Co Ltd', '19,9'),
  ('Yuexiu Property Co Ltd', '43,1'),
  ('Yum China Holdings Inc', '701,0'),
  ('Yunnan Yuntianhua Co Ltd', '2.559,4'),
  ('Yutong Bus Co Ltd', '1.348,9')],
 [('Zai Lab Ltd', '108,7'),
  ('Zhejiang Chint Electrics Co Ltd', '28,2'),
  ('Zhejiang Dingli Machinery Co Ltd', '23,8'),
  ('Zhejiang Sanhua Intelligent Controls Co Ltd', '22,7'),
  ('Zhejiang Supor Co Ltd', '1.004,4'),
  ('Zhejiang Weiming Environment Protection Co Ltd', '152,7'),
  ('ZhongAn Online P&C Insurance Co Ltd', '36,3'),
  ('Zhuzhou CRRC Times Electric Co Ltd', '2.034,6'),
  ('Zoomlion Heavy Industry Science and Technology Co Ltd', '52,3'),
  ('ZTO Express Cayman Inc', '366,8'),
  ('Filippijnen', '27.687,7'),
  ('Aboitiz Power Corp', '45,8'),
  ('ACEN Corp', '153,0'),
  ('AREIT Inc', '208,4'),
  ('Ayala Corp', '2.543,1'),
  ('Ayala Land Inc', '3.582,7'),
  ('Bank of the Philippine Islands', '3.293,1'),
  ('BDO Unibank Inc', '3.724,8'),
  ('Bloomberry Resorts Corp', '441,2'),
  ('GT Capital Holdings Inc', '421,2'),
  ('International Container Terminal Services Inc', '7.360,7'),
  ('Jollibee Foods Corp', '869,2'),
  ('Manila Water Co Inc', '72,1'),
  ('Metropolitan Bank & Trust Co', '1.069,4'),
  ('PLDT Inc', '299,6'),
  ('SM Investments Corp', '1.590,4'),
  ('SM Prime Holdings Inc', '1.134,3'),
  ('Universal Robina Corp', '225,8'),
  ('Hong Kong', '130.263,8'),
  ('AIA Group Ltd', '53.469,5'),
  ('ASMPT Ltd', '410,6'),
  ('Budweiser Brewing Co APAC Ltd', '4.574,9'),
  ('Cathay Pacific Airways Ltd', '1.747,2'),
  ('CK Asset Holdings Ltd', '601,3'),
  ('Dah Sing Banking Group Ltd', '132,5'),
  ('ESR Group Ltd', '713,1'),
  ('Futu Holdings Ltd', '2.863,7'),
  ('Hang Lung Properties Ltd', '532,9'),
  ('Hang Seng Bank Ltd', '4.707,8'),
  ('Henderson Land Development Co Ltd', '2.114,7'),
  ('HKT Trust & HKT Ltd', '1.920,3'),
  ('Hong Kong & China Gas Co Ltd', '3.453,2'),
  ('Hong Kong Exchanges & Clearing Ltd', '25.530,4'),
  ('Hongkong Land Holdings Ltd', '1.727,3'),
  ('Hysan Development Co Ltd', '0,0')],
 [('Link REIT', '7.673,7'),
  ('Luk Fook Holdings International Ltd', '611,5'),
  ('MTR Corp Ltd', '2.701,2'),
  ('Pacific Basin Shipping Ltd', '2.491,9'),
  ('Sands China Ltd', '3.333,7'),
  ('Swire Pacific Ltd', '3.077,1'),
  ('Techtronic Industries Co Ltd', '4.944,2'),
  ('Viva Goods Company Ltd', '93,4'),
  ('Xinyi Glass Holdings Ltd', '151,9'),
  ('Yue Yuen Industrial Holdings Ltd', '685,7'),
  ('India', '287.896,3'),
  ('ABB India Ltd', '4.066,5'),
  ('Aditya Birla Fashion and Retail Ltd', '45,9'),
  ('AIA Engineering Ltd', '43,1'),
  ('APL Apollo Tubes Ltd', '970,4'),
  ('Apollo Hospitals Enterprise Ltd', '9.332,7'),
  ('Apollo Tyres Ltd', '72,5'),
  ('Arvind Fashions Ltd', '472,5'),
  ('Ashok Leyland Ltd', '162,8'),
  ('Asian Paints Ltd', '498,4'),
  ('Astral Ltd', '120,1'),
  ('AU Small Finance Bank Ltd', '118,6'),
  ('Axis Bank Ltd', '11.171,2'),
  ('Bajaj Finance Ltd', '6.483,3'),
  ('Bajaj Finserv Ltd', '734,1'),
  ('Bajaj Holdings & Investment Ltd', '193,9'),
  ('Balkrishna Industries Ltd', '138,5'),
  ('Bank of Baroda', '1.117,5'),
  ('Bank of India', '43,1'),
  ('Bharat Forge Ltd', '1.346,8'),
  ('Bharti Airtel Ltd', '15.090,2'),
  ('Birlasoft Ltd', '335,9'),
  ('Britannia Industries Ltd', '1.392,4'),
  ('BSE Ltd', '685,1'),
  ('Can Fin Homes Ltd', '84,2'),
  ('Canara Bank', '1.489,1'),
  ('Ceat Ltd', '8,8'),
  ('Central Depository Services India Ltd', '2.269,6'),
  ('Cholamandalam Financial Holdings Ltd', '666,7'),
  ('Cholamandalam Investment and Finance Co Ltd', '3.607,6'),
  ('City Union Bank Ltd', '812,2'),
  ('Coforge Ltd', '265,4'),
  ('Computer Age Management Services Ltd', '465,4'),
  ('Container Corp Of India Ltd', '112,2'),
  ('Craftsman Automation Ltd', '750,3'),
  ('CRISIL Ltd', '23,8')],
 [('Cummins India Ltd', '712,2'),
  ('Dalmia Bharat Ltd', '62,0'),
  ("Divi's Laboratories Ltd", '349,1'),
  ('Dixon Technologies India Ltd', '1.613,9'),
  ('DLF Ltd', '5.012,1'),
  ('Dr Lal PathLabs Ltd', '641,6'),
  ('Edelweiss Financial Services Ltd', '31,0'),
  ('Eicher Motors Ltd', '2.128,1'),
  ('Elecon Engineering Co Ltd', '59,2'),
  ('Engineers India Ltd', '96,8'),
  ('Escorts Kubota Ltd', '722,5'),
  ('Federal Bank Ltd', '321,9'),
  ('Finolex Cables Ltd', '114,8'),
  ('Fortis Healthcare Ltd', '267,0'),
  ('FSN E-Commerce Ventures Ltd', '254,4'),
  ('GMR Airports Ltd', '85,4'),
  ('Go Fashion India Ltd', '95,2'),
  ('Godrej Properties Ltd', '6.819,9'),
  ('Gujarat Fluorochemicals Ltd', '85,5'),
  ('Gujarat Gas Ltd', '33,6'),
  ('Gujarat Pipavav Port Ltd', '774,9'),
  ('Havells India Ltd', '3.632,4'),
  ('HCL Technologies Ltd', '12.559,5'),
  ('HDFC Asset Management Co Ltd', '1.216,7'),
  ('HDFC Bank Ltd', '28.917,8'),
  ('HDFC Life Insurance Co Ltd', '3.613,7'),
  ('Hero MotoCorp Ltd', '1.391,2'),
  ('Hindalco Industries Ltd', '8.940,7'),
  ('Hindustan Unilever Ltd', '5.319,4'),
  ('ICICI Bank Ltd', '18.719,5'),
  ('ICICI Lombard General Insurance Co Ltd', '1.332,0'),
  ('ICICI Prudential Life Insurance Co Ltd', '1.216,4'),
  ('IndiaMart InterMesh Ltd', '516,5'),
  ('Indian Energy Exchange Ltd', '263,7'),
  ('Indian Hotels Co Ltd/The', '2.999,8'),
  ('Indian Oil Corp Ltd', '834,3'),
  ('Indian Railway Catering & Tourism Corp Ltd', '120,0'),
  ('Indian Renewable Energy Development Agency Ltd', '54,4'),
  ('Indus Towers Ltd', '236,3'),
  ('IndusInd Bank Ltd', '1.942,8'),
  ('Info Edge India Ltd', '1.640,1'),
  ('Infosys Ltd', '31.793,7'),
  ('InterGlobe Aviation Ltd', '809,4'),
  ('IRB Infrastructure Developers Ltd', '406,3'),
  ('ITD Cementation India Ltd', '535,8'),
  ('Jammu & Kashmir Bank Ltd/The', '210,7')],
 [('Jindal Stainless Ltd', '271,9'),
  ('Jio Financial Services Ltd', '1.896,4'),
  ('JK Cement Ltd', '95,6'),
  ('JSW Energy Ltd', '128,5'),
  ('Jubilant Foodworks Ltd', '604,6'),
  ('Jyothy Labs Ltd', '236,6'),
  ('Kalyan Jewellers India Ltd', '1.155,8'),
  ('Kansai Nerolac Paints Ltd', '12,4'),
  ('Karur Vysya Bank Ltd/The', '644,1'),
  ('KEI Industries Ltd', '115,4'),
  ('Kfin Technologies Ltd', '180,9'),
  ('Kirloskar Oil Engines Ltd', '214,2'),
  ('KPIT Technologies Ltd', '560,2'),
  ('LIC Housing Finance Ltd', '804,3'),
  ('Linde India Ltd', '50,6'),
  ('Macrotech Developers Ltd', '2.253,3'),
  ('Mahanagar Gas Ltd', '806,2'),
  ('Mahindra & Mahindra Financial Services Ltd', '62,8'),
  ('Manappuram Finance Ltd', '317,6'),
  ('Marico Ltd', '702,8'),
  ('Maruti Suzuki India Ltd', '1.502,4'),
  ('Max Financial Services Ltd', '125,3'),
  ('Max Healthcare Institute Ltd', '8.978,0'),
  ('Motherson Sumi Wiring India Ltd', '575,4'),
  ('Motilal Oswal Financial Services Ltd', '769,3'),
  ('Mphasis Ltd', '1.446,0'),
  ('Multi Commodity Exchange of India Ltd', '625,9'),
  ('Muthoot Finance Ltd', '882,2'),
  ('Narayana Hrudayalaya Ltd', '585,8'),
  ('NCC Ltd/India', '13,7'),
  ('NHPC Ltd', '126,5'),
  ('Nippon Life India Asset Management Ltd', '312,5'),
  ('Nuvama Wealth Management Ltd', '107,0'),
  ('One 97 Communications Ltd', '149,0'),
  ('Oracle Financial Services Software Ltd', '628,4'),
  ('Page Industries Ltd', '1.022,6'),
  ('PB Fintech Ltd', '1.783,7'),
  ('Persistent Systems Ltd', '442,3'),
  ('Phoenix Mills Ltd/The', '1.205,7'),
  ('Pidilite Industries Ltd', '646,4'),
  ('PNB Housing Finance Ltd', '786,1'),
  ('Polycab India Ltd', '270,3'),
  ('Power Grid Corp of India Ltd', '4.815,6'),
  ('Punjab National Bank', '1.734,2'),
  ('REC Ltd', '4.226,6'),
  ('Samvardhana Motherson International Ltd', '630,0')],
 [('SBI Life Insurance Co Ltd', '3.097,7'),
  ('Schaeffler India Ltd', '62,5'),
  ('Shriram Finance Ltd', '2.315,4'),
  ('Siemens Ltd', '278,6'),
  ('SKF India Ltd', '25,1'),
  ('Supreme Industries Ltd', '911,8'),
  ('Suzlon Energy Ltd', '475,9'),
  ('Tata Consumer Products Ltd', '292,7'),
  ('Tata Elxsi Ltd', '90,1'),
  ('Tata Power Co Ltd/The', '293,2'),
  ('Tech Mahindra Ltd', '1.143,7'),
  ('Titan Co Ltd', '605,4'),
  ('Torrent Pharmaceuticals Ltd', '1.141,4'),
  ('Trent Ltd', '4.644,0'),
  ('Triveni Turbine Ltd', '737,4'),
  ('Union Bank of India Ltd', '625,7'),
  ('UTI Asset Management Co Ltd', '213,2'),
  ('V-Mart Retail Ltd', '127,6'),
  ('Voltas Ltd', '801,1'),
  ('Wipro Ltd', '3.370,3'),
  ('ZF Commercial Vehicle Control Systems India Ltd', '12,6'),
  ('Zomato Ltd', '6.430,8'),
  ('Indonesië', '78.161,9'),
  ('Aneka Tambang Tbk', '63,5'),
  ('Aspirasi Hidup Indonesia Tbk PT', '242,8'),
  ('Bank Central Asia Tbk PT', '23.258,0'),
  ('Bank CIMB Niaga Tbk PT', '30,8'),
  ('Bank Jago Tbk PT', '79,8'),
  ('Bank Mandiri Persero Tbk PT', '7.933,8'),
  ('Bank Negara Indonesia Persero Tbk PT', '9.570,9'),
  ('Bank Rakyat Indonesia Persero Tbk PT', '21.900,4'),
  ('Bank Syariah Indonesia Tbk PT', '1.644,5'),
  ('Chandra Asri Pacific Tbk PT', '423,8'),
  ('Dayamitra Telekomunikasi PT', '16,6'),
  ('Indofood CBP Sukses Makmur Tbk PT', '1.456,6'),
  ('Indosat Tbk PT', '94,9'),
  ('Jasa Marga Persero Tbk PT', '61,4'),
  ('Map Aktif Adiperkasa PT', '110,1'),
  ('MD Entertainment Tbk PT', '52,5'),
  ('Merdeka Copper Gold Tbk PT', '324,2'),
  ('Pakuwon Jati Tbk PT', '826,9'),
  ('Perusahaan Gas Negara Tbk PT', '7,6'),
  ('Sarana Menara Nusantara Tbk PT', '358,5'),
  ('Telkom Indonesia Persero Tbk PT', '6.978,2'),
  ('Vale Indonesia Tbk PT', '2.469,5'),
  ('XL Axiata Tbk PT', '256,7')],
 [('Israël', '50.388,7'),
  ('Bank Hapoalim BM', '120,7'),
  ('Camtek Ltd/Israel', '737,0'),
  ('Check Point Software Technologies Ltd', '24.107,5'),
  ('Clal Insurance Enterprises Holdings Ltd', '53,5'),
  ('CyberArk Software Ltd', '4.312,1'),
  ('FIBI Holdings Ltd', '54,0'),
  ('Migdal Insurance & Financial Holdings Ltd', '137,3'),
  ('Monday.com Ltd', '1.462,9'),
  ('Nice Ltd', '1.650,9'),
  ('Nova Ltd', '2.551,2'),
  ('RADWARE Ltd', '387,9'),
  ('SimilarWeb Ltd', '695,4'),
  ('Teva Pharmaceutical Industries Ltd', '2.160,0'),
  ('Tower Semiconductor Ltd', '1.233,6'),
  ('Wix.com Ltd', '9.218,1'),
  ('ZIM Integrated Shipping Services Ltd', '1.506,9'),
  ('Japan', '985.252,6'),
  ('Activia Properties Inc', '0,0'),
  ('Advance Residence Investment Corp', '596,8'),
  ('Advantest Corp', '4.380,3'),
  ('Aeon Delight Co Ltd', '2.838,1'),
  ('AEON Financial Service Co Ltd', '132,5'),
  ('Aeon Mall Co Ltd', '1.337,6'),
  ('AEON REIT Investment Corp', '0,0'),
  ('Air Water Inc', '568,6'),

In [13]:
tabs2=sum(tabs, [])

In [15]:
table = pd.DataFrame(tabs2, columns=["share", "amount x €1000"])
table

                                            share amount x €1000
0                                          Afrika       87.955,7
1                                          Egypte          487,6
2     Commercial International Bank - Egypt (CIB)          487,6
3                                     Zuid-Afrika       87.468,1
4                     Anglo American Platinum Ltd          168,6
...                                           ...            ...
2511                               Bancolombia SA        1.112,7
2512               Interconexion Electrica SA ESP          123,8
2513                                         Peru       10.053,7
2514                                Credicorp Ltd       10.053,7
2515                                       Totaal   16.909.150,9

[2516 rows x 2 columns]

In [16]:
table2 = table.drop([0, 1, 3, 38, 39, 239, 257, 284, 458, 475, 719, 721, 727, 753, 757, 775, 799, 883, 924, 936, 938, 1019, 1020, 1035, 1052, 1105, 1120, 1175, 1184, 1189, 1193, 1221, 1255, 1275, 1284, 1302, 1306, 1336, 1360, 1364, 1382, 1467, 1506, 1545, 1546, 1634, 1662, 2385, 2386, 2443, 2446, 2447, 2497, 2510, 2513])

In [17]:
table2

                                            share amount x €1000
2     Commercial International Bank - Egypt (CIB)          487,6
4                     Anglo American Platinum Ltd          168,6
5                           Anglogold Ashanti Plc        4.441,8
6                                    Bid Corp Ltd          624,4
7                       Capitec Bank Holdings Ltd        4.625,4
...                                           ...            ...
2509        Sociedad Quimica y Minera de Chile SA        1.754,1
2511                               Bancolombia SA        1.112,7
2512               Interconexion Electrica SA ESP          123,8
2514                                Credicorp Ltd       10.053,7
2515                                       Totaal   16.909.150,9

[2461 rows x 2 columns]

In [18]:
table2.to_csv("bpfbouw.csv")