In [1]:
import pandas as pd

In [2]:
df = pd.read_json("Aandelen_2024Q4 (1).json")

In [3]:
df

,Onderneming,Land,Sector,BelangEur
0,1&1 AG,Duitsland,Telecommunicatiediensten,268859
1,360 SECURITY TECHNOLOGY IN-A,China,Software & Diensten,722465
2,37 INTERACTIVE ENTERTAINME-A,China,Media & Entertainment,319282
3,3I GROUP PLC,Verenigd Koninkrijk,Financiële Dienstverlening,19236644
4,3M INDIA LTD,India,Kapitaalgoederen,1552003
...,...,...,...,...
3879,ZSCALER INC,Verenigde Staten,Software & Diensten,5395400
3880,ZTE CORP-A,China,Technologie Hardware & Apparatuur,2203150
3881,ZTE CORP-H,China,Technologie Hardware & Apparatuur,4449876
3882,ZURICH INSURANCE GROUP AG,Zwitserland,Verzekeringen,45845735
3883,ZYDUS LIFESCIENCES LTD,India,"Farmaceutica, Biotechnologie & Levenswetenscha...",6730104

In [8]:
df = df.rename(columns={"Onderneming": "Naam"})

In [5]:
df2 = pd.read_json("Obligaties_2024Q4.json")

In [9]:
df3 = pd.merge(df, df2, "outer")

In [10]:
df3

,Naam,Land,Sector,BelangEur
0,1&1 AG,Duitsland,Telecommunicatiediensten,268859
1,360 SECURITY TECHNOLOGY IN-A,China,Software & Diensten,722465
2,37 INTERACTIVE ENTERTAINME-A,China,Media & Entertainment,319282
3,3Cime S.A,Italie,Gezondheidszorg,661599
4,3I GROUP PLC,Verenigd Koninkrijk,Financiële Dienstverlening,19236644
...,...,...,...,...
5449,de Volksbank N.V.,Nederland,Staatseigendom zonder garantie,10853145
5450,goeasy Ltd.,Canada,Financiële maatschappijen,3647220
5451,"iHeartMedia, Inc.",Verenigde Staten,Media en entertainment,5590270
5452,"loanDepot, Inc.",Verenigde Staten,Financiële maatschappijen,1579322
5453,Ørsted A/S,Denemarken,Staatseigendom zonder garantie,11615069

In [11]:
df3.to_clipboard()